spring:
  application:
    name: LearnMate

  config:
    import: "optional:file:.env[.properties]"

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret_key: ${JWT_SECRET_KEY}
  access_token_expire: ${JWT_ACCESS_TOKEN_EXPIRE}
  refresh_token_expire: ${JWT_REFRESH_TOKEN_EXPIRE}
