name: Build and Deploy with JIB

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: Build and push Docker image with JIB
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          ./gradlew jib -Djib.to.auth.username=$DOCKER_USERNAME -Djib.to.auth.password=$DOCKER_PASSWORD \
            -Djib.to.image=$DOCKER_USERNAME/learnmate:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Connect to EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Stop and remove any existing application container
            docker-compose down || true
            # Pull the latest image
            docker pull ${{ secrets.DOCKER_USERNAME }}/learnmate:latest
            # Start application with docker-compose
            docker-compose up -d