name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v2

      - name: Java 버전 설정
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: GitHub Secrets 출력 확인 (디버깅)
        run: |
          echo "DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}"
          echo "EC2_HOST: ${{ secrets.EC2_HOST }}"
          echo "DATABASE_URL: ${{ secrets.DATABASE_URL }}"
          echo "DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}"

      - name: Docker 로그인
        run: |
          echo "Docker Username: ${{ secrets.DOCKER_USERNAME }}"  # 추가 확인
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: JIB로 Docker 이미지 빌드 및 푸시
        run: |
          echo "Building Docker image with username: ${{ secrets.DOCKER_USERNAME }}"
          ./gradlew jib --image=${{ secrets.DOCKER_USERNAME }}/learnmate:latest

      - name: EC2에 Docker 컨테이너 배포
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ssh_key
          chmod 600 ssh_key
          ssh -o StrictHostKeyChecking=no -i ssh_key ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            echo "DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}"  # DOCKER_USERNAME 값 확인

            # 최신 이미지를 가져옵니다.
            docker pull ${{ secrets.DOCKER_USERNAME }}/learnmate:latest

            # 기존 컨테이너 중지 및 제거
            docker stop learnmate-app || true
            docker rm learnmate-app || true

            # 새 컨테이너 실행
            docker run -d \
              --name learnmate-app \
              -p 8080:8080 \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              -e DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} \
              -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
              ${{ secrets.DOCKER_USERNAME }}/learnmate:latest
          EOF